// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bpuuoaarnitqcucskxbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdXVvYWFybml0cWN1Y3NreGJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTQ5ODEsImV4cCI6MjA3MTQ3MDk4MX0.zWZcXTnuD70VmY5VJeAo-L3p8_LYie8E3IgkNhs9VGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});